### ISSUE TITLE
Title bar

### ISSUE THREAD

**Issue by luwes** [aytee17/vscode-oceanic-next-sublime#1]
Thanks for this great theme! The best Vscode version of Oceanic I found.

Would be nice to make the title bar also like the darker color.

Workaround for now is adding this to `settings.json`

```js
	"workbench.colorCustomizations": {
		"titleBar.activeBackground": "#092028",
		"titleBar.activeForeground": "#A7ADBA",
		"titleBar.inactiveBackground": "#092028",
		"titleBar.inactiveForeground": "#A7ADBA"
	},
```

**Comment by aytee17** [comment]
I'm not particularly attached to the current title bar, but I want to make sure the theme looks as much like sublime + oceanic next as possible, to stay true to the name, and to help people transition. 

I actually use [Titlebar-Less](https://marketplace.visualstudio.com/items?itemName=lehni.vscode-titlebar-less-macos), it gets rid of the title bar altogether.
