### ISSUE TITLE
Editor ruler doesn't match colors

### ISSUE THREAD

**Issue by luwes** [aytee17/vscode-oceanic-next-sublime#2]
`editorRuler.foreground` seems not defined and doesn't match the theme really.

Workaround is adding this to `settings.json`

```js
	"workbench.colorCustomizations": {
		"editorRuler.foreground": "#ffffff22"
	},
```

**Comment by aytee17** [comment]
Thanks for the heads up. I just published a patch with the setting you provided, it looks great.
