### ISSUE TITLE
Hover popup box background color

### ISSUE THREAD

**Issue by luwes** [aytee17/vscode-oceanic-next-sublime#3]
The popup box bg color doesn't match the theme.

<img width="337" alt="screen shot 2018-10-23 at 10 05 34 pm" src="https://user-images.githubusercontent.com/360826/47401810-c509c300-d710-11e8-82d2-5eedb54e3857.png">

**Comment by aytee17** [comment]
I've adjusted the colour to be in between the editor background and the sidebar background. See how you go with it.

**Comment by luwes** [comment]
Awesome, looks great. thank you!
