### ISSUE TITLE
Activity bar badge background color alerting

### ISSUE THREAD

**Issue by luwes** [aytee17/vscode-oceanic-next-sublime#4]
This might be subjective but I found the red bg color of the badge too alerting.
Getting the feeling you need to check it all the time 😄 

A nice toned down version is

`"activityBarBadge.background": "#4178A3"`

**Comment by aytee17** [comment]
Nice. I have the activity bar turned off so I never noticed, but it was pretty distracting when I turned it on. Fixed in v0.0.21.
